server:
  port: 8888

spring:
  application:
    name: Gateway
  cloud:
    discovery:
      enabled: true
    gateway:
      mvc:
        routes:
          - id: r1
            uri: http://localhost:8080/
            predicates:
              - Path=/clients/**
  main:
    web-application-type: reactive
eureka:
  instance:
    hostname: localhost

